version: '3'

services:
  web:
    image: salary_calculator
    container_name: salary_calculator
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Production
