version: '3'

services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_DB: salary_calculator_db
      POSTGRES_USER: salary_app
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
       - mynetwork

  web:
    image: salary_calculator
    container_name: salary_calculator
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - postgres
    networks:
       - mynetwork

networks:
  mynetwork:
     driver: bridge